In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
ser = pd.Series()
ser

Series([], dtype: object)

In [5]:
data = np.array(['g','e','e','k', 's'])

ser = pd.Series(data)
print(ser)

0    g
1    e
2    e
3    k
4    s
dtype: str

In [6]:
# from a list
data = ['g', 'e', 'e', 'k', 's']
ser = pd.Series(data)
print(ser)

0    g
1    e
2    e
3    k
4    s
dtype: str

In [7]:
# using numpy function

ser = pd.Series(np.linspace(1, 10, 5))
ser

0     1.00
1     3.25
2     5.50
3     7.75
4    10.00
dtype: float64

In [ ]:
#using arange function
ser = pd.Series(np.arange(6, 20, 2))
ser

0     6
1     8
2    10
3    12
4    14
5    16
6    18
dtype: int64

In [13]:
# Pandas DataFrame
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [14]:
lst = ['series', 'dataframe', 'panel']
df = pd.DataFrame(lst)
print(df)

           0
0     series
1  dataframe
2      panel

In [15]:
data = {
    'a': np.array([2, 3, 4]),
    'b': np.array([4, 5, 4]),
    'c': np.array([3,4 ,5])
}
df = pd.DataFrame(data)
print(df)

   a  b  c
0  2  4  3
1  3  5  4
2  4  4  5

In [17]:
# setting a custom index 
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)
res = df.set_index('Age')
print(res)

        Name         City
Age
25     Alice     New York
30       Bob  Los Angeles
35   Charlie      Chicago

In [18]:
# to reset index to default
res = df.reset_index(drop=True)
print(res)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [ ]:
# indexing with loc
df = pd.DataFrame(data, index=['A', 'B', 'C'])
print(df)
print(df.loc['A'])

      Name  Age         City
A    Alice   25     New York
B      Bob   30  Los Angeles
C  Charlie   35      Chicago
Name       Alice
Age           25
City    New York
Name: A, dtype: object

In [23]:
# accessing row by index
# iloc -> for positional indexing
# loc -> for label based indexing
second_row = df.iloc[0]
print(second_row)

Name       Alice
Age           25
City    New York
Name: A, dtype: object

In [26]:
# access multiple rows
multiple_rows = df.loc['A':'C', ['Name', 'Age']]
print(multiple_rows)

      Name  Age
A    Alice   25
B      Bob   30
C  Charlie   35

In [27]:
# access value at specific cell using at and iat
age_at_index = df.at['A', 'Age']
print(age_at_index)

25

In [29]:
# iat
Name_at_index = df.iat[2, 1]
print(Name_at_index)

35

In [2]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('C:\\Users\\kgaga\\Desktop\\AI_LEARNING_JOURNEY\\Crop_recommendation (1).csv')

In [6]:
df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [7]:
# retrieve single column
first = df['K']
print(first)

0       43
1       41
2       44
3       40
4       42
        ..
2195    32
2196    27
2197    30
2198    34
2199    30
Name: K, Length: 2200, dtype: int64

In [9]:
ft = df[['N','P', 'K']]
print(ft)

        N   P   K
0      90  42  43
1      85  58  41
2      60  55  44
3      74  35  40
4      78  42  42
...   ...  ..  ..
2195  107  34  32
2196   99  15  27
2197  118  33  30
2198  117  32  34
2199  104  18  30

[2200 rows x 3 columns]

In [11]:
# retrieve single row
row = df.loc[4]
row

N                     78
P                     42
K                     42
temperature    20.130175
humidity       81.604873
ph              7.628473
rainfall       262.71734
label               rice
Name: 4, dtype: object

In [12]:
# select specific rows and columns by position
st = df.iloc[[3, 44, 5], [5, 4]]
print(st)

          ph   humidity
3   6.980401  80.158363
44  7.224286  82.366990
5   7.073454  83.370118

In [ ]:
# select all rows and spefici columns
# iloc needs numeric values for indexing
s1 = df.iloc[:, [0, 4, 5]]
print(s1)

        N   humidity        ph
0      90  82.002744  6.502985
1      85  80.319644  7.038096
2      60  82.320763  7.840207
3      74  80.158363  6.980401
4      78  81.604873  7.628473
...   ...        ...       ...
2195  107  66.413269  6.780064
2196   99  56.636362  6.086922
2197  118  67.225123  6.362608
2198  117  52.127394  6.758793
2199  104  60.396475  6.779833

[2200 rows x 3 columns]

In [17]:
dy = df[df['N'] > 75]
print(dy)

        N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
7      94  53  40    20.277744  82.894086  5.718627  241.974195    rice
8      89  54  38    24.515881  83.535216  6.685346  230.446236    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[675 rows x 8 columns]

In [20]:

custom = df.iloc[8:732]
print(custom)

     P   K  temperature   humidity        ph    rainfall      label
N
89  54  38    24.515881  83.535216  6.685346  230.446236       rice
68  58  38    23.223974  83.033227  6.336254  221.209196       rice
91  53  40    26.527235  81.417538  5.386168  264.614870       rice
90  46  42    23.978982  81.450616  7.502834  250.083234       rice
78  58  44    26.800796  80.886848  5.108682  284.436457       rice
..  ..  ..          ...        ...       ...         ...        ...
48  62  15    25.365861  66.637972  7.538631   65.816559  blackgram
32  66  17    34.946616  65.267740  7.162358   70.141514  blackgram
21  63  22    25.097374  67.728379  6.859409   74.616499  blackgram
20  72  19    32.476483  64.348487  7.397191   65.820457  blackgram
25  65  21    33.863512  68.592323  6.880246   69.244641  blackgram

[724 rows x 7 columns]

In [23]:
df = pd.read_csv('C:\\Users\\kgaga\\Desktop\\AI_LEARNING_JOURNEY\\Titanic-Dataset.csv')

In [24]:
data = pd.DataFrame(df)
display(data)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [25]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [26]:
display(data.loc[
    (data['Age'] > 30) &
    (data['Fare'] > 70) &
    (data['PassengerId'] < 5) &
    (data['Name'].str.startswith('C')),
    ['Name', 'Ticket']
])

                                                Name    Ticket
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  PC 17599

In [29]:
filtered_values = np.where(
    (data['Age'] > 30) &
    (data['Fare'] > 70) &
    (data['PassengerId'] < 5) &
    (data['Name'].str.startswith('C'))
)

print(filtered_values)

display(data.iloc[filtered_values])

(array([1]),)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

Pandas Merging, joining and Concatenating

In [1]:
import numpy as np
import pandas as pd

In [7]:
import pandas as pd

data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd'],
         'Mobile No': [97, 91, 58, 76]}

data2 = {'Name': ['Gaurav', 'Anuj', 'Dhiraj', 'Hitesh'],
         'Age': [22, 32, 12, 52],
         'Address': ['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
         'Qualification': ['MCA', 'Phd', 'Bcom', 'B.hons'],
         'Salary': [1000, 2000, 3000, 4000]}

df = pd.DataFrame(data1, index=[0, 1, 2, 3])

df1 = pd.DataFrame(data2, index=[2, 3, 6, 7])

print(df, "\n\n", df1)

     Name  Age    Address Qualification  Mobile No
0     Jai   27     Nagpur           Msc         97
1  Princi   24     Kanpur            MA         91
2  Gaurav   22  Allahabad           MCA         58
3    Anuj   32    Kannuaj           Phd         76

      Name  Age    Address Qualification  Salary
2  Gaurav   22  Allahabad           MCA    1000
3    Anuj   32    Kannuaj           Phd    2000
6  Dhiraj   12  Allahabad          Bcom    3000
7  Hitesh   52    Kannuaj        B.hons    4000

In [8]:
frames = [df, df1]
res1 = pd.concat(frames)
res1

     Name  Age    Address Qualification  Mobile No  Salary
0     Jai   27     Nagpur           Msc       97.0     NaN
1  Princi   24     Kanpur            MA       91.0     NaN
2  Gaurav   22  Allahabad           MCA       58.0     NaN
3    Anuj   32    Kannuaj           Phd       76.0     NaN
2  Gaurav   22  Allahabad           MCA        NaN  1000.0
3    Anuj   32    Kannuaj           Phd        NaN  2000.0
6  Dhiraj   12  Allahabad          Bcom        NaN  3000.0
7  Hitesh   52    Kannuaj        B.hons        NaN  4000.0

.concat using logic on axes
axes join = inner -> keeps only the common columns
axes join = outer -> gives union of all the dataFrames

In [9]:
res2 = pd.concat([df, df1], axis=1, join='inner')
res2

,Name,Age,Address,Qualification,Mobile No,Name,Age,Address,Qualification,Salary
2,Gaurav,22,Allahabad,MCA,58,Gaurav,22,Allahabad,MCA,1000
3,Anuj,32,Kannuaj,Phd,76,Anuj,32,Kannuaj,Phd,2000

In [10]:
res3 = pd.concat([df, df1], axis=1, join='outer')
res3

,Name,Age,Address,Qualification,Mobile No,Name,Age,Address,Qualification,Salary
0,Jai,27.0,Nagpur,Msc,97.0,NaN,NaN,NaN,NaN,NaN
1,Princi,24.0,Kanpur,MA,91.0,NaN,NaN,NaN,NaN,NaN
2,Gaurav,22.0,Allahabad,MCA,58.0,Gaurav,22.0,Allahabad,MCA,1000.0
3,Anuj,32.0,Kannuaj,Phd,76.0,Anuj,32.0,Kannuaj,Phd,2000.0
6,NaN,NaN,NaN,NaN,NaN,Dhiraj,12.0,Allahabad,Bcom,3000.0
7,NaN,NaN,NaN,NaN,NaN,Hitesh,52.0,Kannuaj,B.hons,4000.0